/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generated message schema for the "collatz" Free Agent application. Source of truth is the application's pydantic models; regenerate with `freeagent schema` rather than editing by hand (ADR-0007).
 */
export type CollatzMessages = Chain;
export type MessageType = "Chain";
export type Numbers = number[];
export type Protocol = string | null;

/**
 * A Collatz chain in progress: the sequence of numbers produced so far.
 *
 * Starts as a single starting number and grows by one :func:`collatz_step` each time an agent
 * extends it. The chain is *complete* once it reaches 1 (see :func:`is_complete`), the fixed point
 * of the Collatz map -- the environment watches for that to know when an agent is finished.
 *
 * :ivar numbers: The chain so far, oldest first; never empty in normal use. Its last element is
 *     the current value the next step extends.
 */
export interface Chain {
  message_type: MessageType;
  numbers: Numbers;
  protocol?: Protocol;
}
